// Norwegian bank brands with realistic AI visibility monitoring data

export const brands = [
  {
    id: "brand_1",
    name: "DNB",
    domain: "dnb.no",
    logo: "DNB",
    nameVariations: ["DNB", "DNB Bank", "DNB ASA", "Den Norske Bank"],
    visibilityScore: 78,
    previousScore: 72,
    mentionsThisWeek: 47,
    citationsThisWeek: 23,
    color: "#004D40",
  },
  {
    id: "brand_2",
    name: "Nordea Norge",
    domain: "nordea.no",
    logo: "Nordea",
    nameVariations: ["Nordea", "Nordea Norge", "Nordea Bank Norge", "Nordea Bank"],
    visibilityScore: 65,
    previousScore: 61,
    mentionsThisWeek: 34,
    citationsThisWeek: 15,
    color: "#0000A0",
  },
  {
    id: "brand_3",
    name: "SpareBank 1",
    domain: "sparebank1.no",
    logo: "SB1",
    nameVariations: ["SpareBank 1", "Sparebank1", "SB1", "SpareBank 1 SR-Bank", "SpareBank 1 SMN", "SpareBank 1 Nord-Norge"],
    visibilityScore: 52,
    previousScore: 48,
    mentionsThisWeek: 28,
    citationsThisWeek: 11,
    color: "#E31837",
  },
  {
    id: "brand_4",
    name: "Handelsbanken Norge",
    domain: "handelsbanken.no",
    logo: "HB",
    nameVariations: ["Handelsbanken", "Handelsbanken Norge", "Svenska Handelsbanken Norge"],
    visibilityScore: 41,
    previousScore: 44,
    mentionsThisWeek: 15,
    citationsThisWeek: 6,
    color: "#005FA0",
  },
  {
    id: "brand_5",
    name: "Storebrand",
    domain: "storebrand.no",
    logo: "SB",
    nameVariations: ["Storebrand", "Storebrand Bank", "Storebrand ASA", "Storebrand Livsforsikring"],
    visibilityScore: 58,
    previousScore: 53,
    mentionsThisWeek: 31,
    citationsThisWeek: 14,
    color: "#00205B",
  },
  {
    id: "brand_6",
    name: "KLP",
    domain: "klp.no",
    logo: "KLP",
    nameVariations: ["KLP", "Kommunal Landspensjonskasse", "KLP Banken"],
    visibilityScore: 35,
    previousScore: 32,
    mentionsThisWeek: 12,
    citationsThisWeek: 4,
    color: "#00843D",
  },
  {
    id: "brand_7",
    name: "Sbanken",
    domain: "sbanken.no",
    logo: "Sb",
    nameVariations: ["Sbanken", "Skandiabanken", "S-banken"],
    visibilityScore: 44,
    previousScore: 47,
    mentionsThisWeek: 19,
    citationsThisWeek: 8,
    color: "#FF6B00",
  },
  {
    id: "brand_8",
    name: "Danske Bank Norge",
    domain: "danskebank.no",
    logo: "DB",
    nameVariations: ["Danske Bank", "Danske Bank Norge", "Danske Bank AS"],
    visibilityScore: 39,
    previousScore: 36,
    mentionsThisWeek: 14,
    citationsThisWeek: 5,
    color: "#003755",
  },
];

export const platforms = [
  { id: "chatgpt", name: "ChatGPT", icon: "openai" },
  { id: "perplexity", name: "Perplexity", icon: "perplexity" },
];

// Visibility trend data (last 30 days)
export const visibilityTrends = [
  { date: "9 jan", DNB: 68, Nordea: 58, SpareBank1: 45, Storebrand: 49 },
  { date: "12 jan", DNB: 70, Nordea: 59, SpareBank1: 44, Storebrand: 50 },
  { date: "15 jan", DNB: 69, Nordea: 60, SpareBank1: 46, Storebrand: 51 },
  { date: "18 jan", DNB: 71, Nordea: 58, SpareBank1: 47, Storebrand: 50 },
  { date: "21 jan", DNB: 73, Nordea: 61, SpareBank1: 46, Storebrand: 52 },
  { date: "24 jan", DNB: 72, Nordea: 62, SpareBank1: 48, Storebrand: 53 },
  { date: "27 jan", DNB: 74, Nordea: 60, SpareBank1: 49, Storebrand: 51 },
  { date: "30 jan", DNB: 75, Nordea: 63, SpareBank1: 48, Storebrand: 54 },
  { date: "2 feb", DNB: 76, Nordea: 64, SpareBank1: 50, Storebrand: 55 },
  { date: "5 feb", DNB: 78, Nordea: 65, SpareBank1: 52, Storebrand: 58 },
];

// Platform breakdown
export const platformBreakdown = [
  { platform: "ChatGPT", mentions: 124, citations: 52, avgScore: 62 },
  { platform: "Perplexity", mentions: 87, citations: 41, avgScore: 71 },
];

// Recent mentions
export const recentMentions = [
  {
    id: "m1",
    brandId: "brand_1",
    brandName: "DNB",
    platform: "ChatGPT",
    query: "Hvilken bank er best for boliglån i Norge?",
    response: "DNB er en av de største bankene i Norge og tilbyr konkurransedyktige boliglånsrenter. De har et bredt utvalg av låneprodukter, inkludert fastrentelån og flytende rente...",
    mentionType: "recommendation",
    sentiment: "positive",
    citationUrl: "https://www.dnb.no/lan/boliglan",
    hasCitation: true,
    timestamp: "2026-02-08T10:23:00Z",
  },
  {
    id: "m2",
    brandId: "brand_2",
    brandName: "Nordea Norge",
    platform: "Perplexity",
    query: "Sammenlign sparerenter i norske banker 2026",
    response: "Nordea tilbyr innskuddsrenter som varierer basert på kontotype og innskuddsbeløp. For høyrentekontoer kan du forvente renter rundt 3,5-4%...",
    mentionType: "comparison",
    sentiment: "neutral",
    citationUrl: "https://www.nordea.no/privat/sparing",
    hasCitation: true,
    timestamp: "2026-02-08T09:15:00Z",
  },
  {
    id: "m3",
    brandId: "brand_3",
    brandName: "SpareBank 1",
    platform: "ChatGPT",
    query: "Hva er de beste bankene for bedriftskunder i Norge?",
    response: "SpareBank 1-alliansen er et godt alternativ for bedrifter, særlig i regionene der de har sterk lokal tilstedeværelse. De tilbyr skreddersydde løsninger for SMB-segmentet...",
    mentionType: "recommendation",
    sentiment: "positive",
    citationUrl: null,
    hasCitation: false,
    timestamp: "2026-02-08T08:45:00Z",
  },
  {
    id: "m4",
    brandId: "brand_1",
    brandName: "DNB",
    platform: "Perplexity",
    query: "Beste mobilbank-app i Norge",
    response: "DNBs mobilbank-app er konsekvent rangert som en av de beste i Norge, med funksjoner som Vipps-integrasjon, budsjetteringsverktøy og enkel oversikt over alle kontoer...",
    mentionType: "recommendation",
    sentiment: "positive",
    citationUrl: "https://www.dnb.no/tjenester/mobilbank",
    hasCitation: true,
    timestamp: "2026-02-07T16:30:00Z",
  },
  {
    id: "m5",
    brandId: "brand_5",
    brandName: "Storebrand",
    platform: "ChatGPT",
    query: "Hvilken bank i Norge er best på bærekraftig investering?",
    response: "Storebrand er ledende innen bærekraftige investeringer i Norge. De har et sterkt fokus på ESG-kriterier og tilbyr flere fond med bærekraftsprofil...",
    mentionType: "recommendation",
    sentiment: "positive",
    citationUrl: "https://www.storebrand.no/baerekraft",
    hasCitation: true,
    timestamp: "2026-02-07T14:20:00Z",
  },
  {
    id: "m6",
    brandId: "brand_7",
    brandName: "Sbanken",
    platform: "Perplexity",
    query: "Er Sbanken et godt valg for unge kunder?",
    response: "Sbanken (tidligere Skandiabanken) har vært populær blant yngre kunder på grunn av sine lave gebyrer og brukervennlige digitale tjenester. Etter oppkjøpet av DNB har det imidlertid vært noen endringer...",
    mentionType: "mention",
    sentiment: "mixed",
    citationUrl: null,
    hasCitation: false,
    timestamp: "2026-02-07T11:05:00Z",
  },
  {
    id: "m7",
    brandId: "brand_4",
    brandName: "Handelsbanken Norge",
    platform: "ChatGPT",
    query: "Hvilke banker har de beste vilkårene for forbrukslån?",
    response: "Handelsbanken skiller seg ut med sin desentraliserte modell der lokale kontorer har myndighet til å tilby skreddersydde vilkår. Dette kan gi bedre betingelser for kunder som ønsker personlig rådgivning...",
    mentionType: "mention",
    sentiment: "positive",
    citationUrl: "https://www.handelsbanken.no/privat",
    hasCitation: true,
    timestamp: "2026-02-07T09:50:00Z",
  },
  {
    id: "m8",
    brandId: "brand_6",
    brandName: "KLP",
    platform: "ChatGPT",
    query: "Hvor bør offentlig ansatte i Norge ha pensjon?",
    response: "KLP er den ledende pensjonsleverandøren for offentlig sektor i Norge. Som Kommunal Landspensjonskasse forvalter de pensjonsmidler for kommuner, helseforetak og andre offentlige virksomheter...",
    mentionType: "recommendation",
    sentiment: "positive",
    citationUrl: "https://www.klp.no/pensjon",
    hasCitation: true,
    timestamp: "2026-02-06T15:40:00Z",
  },
  {
    id: "m9",
    brandId: "brand_8",
    brandName: "Danske Bank Norge",
    platform: "Perplexity",
    query: "Danske Bank Norge erfaring og anmeldelser",
    response: "Danske Bank i Norge har gjennomgått omstruktureringer de siste årene. Kundetilfredsheten varierer, men banken tilbyr gode digitale løsninger og konkurransedyktige produkter for privatpersoner...",
    mentionType: "mention",
    sentiment: "neutral",
    citationUrl: null,
    hasCitation: false,
    timestamp: "2026-02-06T12:15:00Z",
  },
  {
    id: "m10",
    brandId: "brand_1",
    brandName: "DNB",
    platform: "ChatGPT",
    query: "Hvilke norske banker tilbyr valutakontoer?",
    response: "DNB er den største norske banken som tilbyr valutakontoer i flere valutaer, inkludert USD, EUR, GBP og SEK. De tilbyr også valutaveksling gjennom nettbanken og mobilappen...",
    mentionType: "mention",
    sentiment: "positive",
    citationUrl: "https://www.dnb.no/bedrift/valuta",
    hasCitation: true,
    timestamp: "2026-02-06T10:30:00Z",
  },
];

// Prompts for AI queries
export const prompts = [
  {
    id: "p1",
    query: "Hvilken bank er best for boliglån i Norge?",
    category: "Boliglån",
    platforms: ["chatgpt", "perplexity"],
    frequency: "daily",
    lastRun: "2026-02-08T06:00:00Z",
    isActive: true,
  },
  {
    id: "p2",
    query: "Sammenlign de største bankene i Norge",
    category: "Generell",
    platforms: ["chatgpt", "perplexity"],
    frequency: "daily",
    lastRun: "2026-02-08T06:00:00Z",
    isActive: true,
  },
  {
    id: "p3",
    query: "Hvilken norsk bank har best kundeservice?",
    category: "Kundeservice",
    platforms: ["chatgpt"],
    frequency: "weekly",
    lastRun: "2026-02-03T06:00:00Z",
    isActive: true,
  },
  {
    id: "p4",
    query: "Beste sparekonto i Norge 2026",
    category: "Sparing",
    platforms: ["chatgpt", "perplexity"],
    frequency: "daily",
    lastRun: "2026-02-08T06:00:00Z",
    isActive: true,
  },
  {
    id: "p5",
    query: "Anbefal en bank for bedriftskunder i Norge",
    category: "Bedrift",
    platforms: ["perplexity"],
    frequency: "weekly",
    lastRun: "2026-02-05T06:00:00Z",
    isActive: true,
  },
  {
    id: "p6",
    query: "Hvilke norske banker er best på bærekraft og ESG?",
    category: "Bærekraft",
    platforms: ["chatgpt", "perplexity"],
    frequency: "weekly",
    lastRun: "2026-02-04T06:00:00Z",
    isActive: false,
  },
  {
    id: "p7",
    query: "Er det trygt å spare i norske banker?",
    category: "Generell",
    platforms: ["chatgpt"],
    frequency: "weekly",
    lastRun: "2026-02-01T06:00:00Z",
    isActive: true,
  },
  {
    id: "p8",
    query: "Beste kredittkort i Norge med reiseforsikring",
    category: "Kredittkort",
    platforms: ["chatgpt", "perplexity"],
    frequency: "daily",
    lastRun: "2026-02-08T06:00:00Z",
    isActive: true,
  },
];

// Competitors (tracked by each brand)
export const competitors = [
  { id: "c1", brandId: "brand_1", competitorBrandId: "brand_2", notes: "Hovudkonkurrent i personmarkedet" },
  { id: "c2", brandId: "brand_1", competitorBrandId: "brand_3", notes: "Sterk i regionale markeder" },
  { id: "c3", brandId: "brand_1", competitorBrandId: "brand_5", notes: "Konkurrerer om pensjonskunder" },
  { id: "c4", brandId: "brand_2", competitorBrandId: "brand_1", notes: "Nordens største bank vs Norges største" },
  { id: "c5", brandId: "brand_2", competitorBrandId: "brand_8", notes: "Nordisk rivalisering" },
  { id: "c6", brandId: "brand_3", competitorBrandId: "brand_1", notes: "Lokal vs nasjonal bank" },
];

// Scheduled jobs
export const scheduledJobs = [
  {
    id: "j1",
    type: "ai_query",
    description: "Daglige AI-spørringer (alle aktive prompts)",
    schedule: "Daglig kl. 06:00",
    status: "active",
    lastRun: "2026-02-08T06:00:00Z",
    nextRun: "2026-02-09T06:00:00Z",
  },
  {
    id: "j2",
    type: "report",
    description: "Ukentlig synlighetsrapport",
    schedule: "Mandager kl. 08:00",
    status: "active",
    lastRun: "2026-02-03T08:00:00Z",
    nextRun: "2026-02-10T08:00:00Z",
  },
  {
    id: "j3",
    type: "score_calculation",
    description: "Daglig beregning av synlighetspoeng",
    schedule: "Daglig kl. 07:00",
    status: "active",
    lastRun: "2026-02-08T07:00:00Z",
    nextRun: "2026-02-09T07:00:00Z",
  },
];

// Subscription tiers
export const subscriptionTiers = [
  {
    id: "starter",
    name: "Starter",
    price: 990,
    currency: "NOK",
    period: "måned",
    features: [
      "1 merkevare",
      "50 AI-spørringer/måned",
      "Grunnleggende analyse",
      "Ukentlig rapport",
      "ChatGPT-sporing",
    ],
    limits: { brands: 1, queries: 50, users: 1 },
  },
  {
    id: "pro",
    name: "Pro",
    price: 2490,
    currency: "NOK",
    period: "måned",
    features: [
      "5 merkevarer",
      "500 AI-spørringer/måned",
      "Avansert analyse",
      "Daglig rapport",
      "ChatGPT + Perplexity",
      "Konkurrentanalyse",
      "API-tilgang",
    ],
    limits: { brands: 5, queries: 500, users: 3 },
    popular: true,
  },
  {
    id: "agency",
    name: "Agency",
    price: 5990,
    currency: "NOK",
    period: "måned",
    features: [
      "25 merkevarer",
      "2 500 AI-spørringer/måned",
      "Full analyse-suite",
      "Daglig rapport",
      "Alle plattformer",
      "White-label rapporter",
      "Prioritert support",
      "Fler-bruker arbeidsområder",
    ],
    limits: { brands: 25, queries: 2500, users: 10 },
  },
  {
    id: "enterprise",
    name: "Enterprise",
    price: null,
    currency: "NOK",
    period: "måned",
    features: [
      "Ubegrenset merkevarer",
      "Ubegrenset spørringer",
      "Tilpassede integrasjoner",
      "Dedikert kontaktperson",
      "SLA-garanti",
      "SSO/SAML",
      "Tilpasset datalagring",
      "On-premise mulighet",
    ],
    limits: { brands: Infinity, queries: Infinity, users: Infinity },
  },
];

// Daily aggregation data
export const dailyAggregations = [
  { date: "2026-02-08", totalMentions: 28, totalCitations: 12, avgScore: 54.2 },
  { date: "2026-02-07", totalMentions: 31, totalCitations: 15, avgScore: 53.8 },
  { date: "2026-02-06", totalMentions: 25, totalCitations: 10, avgScore: 52.9 },
  { date: "2026-02-05", totalMentions: 29, totalCitations: 13, avgScore: 53.1 },
  { date: "2026-02-04", totalMentions: 22, totalCitations: 9, avgScore: 51.7 },
  { date: "2026-02-03", totalMentions: 33, totalCitations: 16, avgScore: 54.5 },
  { date: "2026-02-02", totalMentions: 18, totalCitations: 7, avgScore: 50.3 },
];

// Weekly aggregation data
export const weeklyAggregations = [
  { week: "Uke 6 (3-9 feb)", totalMentions: 186, totalCitations: 82, avgScore: 53.6 },
  { week: "Uke 5 (27 jan-2 feb)", totalMentions: 172, totalCitations: 74, avgScore: 52.1 },
  { week: "Uke 4 (20-26 jan)", totalMentions: 158, totalCitations: 68, avgScore: 50.8 },
  { week: "Uke 3 (13-19 jan)", totalMentions: 143, totalCitations: 59, avgScore: 49.2 },
];

// KPI summary
export const kpiSummary = {
  totalBrands: 8,
  activeBrands: 8,
  totalMentionsThisWeek: 200,
  mentionsChange: +14.3,
  totalCitationsThisWeek: 86,
  citationsChange: +10.8,
  averageVisibilityScore: 51.5,
  scoreChange: +3.2,
  activePrompts: 7,
  scheduledQueries: 42,
};
